services:
  db:
    image: postgres:16
    container_name: booking_swps_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-non-dev
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: booking_swps_redis

  akvalenok_app:
    image: booking_swps_app
    build:
      context: .
    container_name: booking_swps_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: ["/akvalenok/docker/app.sh"]
    # command: sh -c "alembic upgrade head && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - "7777:8000"

  celery:
    image: booking_swps_celery
    build:
      context: . # celery это библиотека, у неё нет образа, берём из основного build
    container_name: booking_swps_celery
    command: [ "/akvalenok/docker/celery.sh", "celery" ] # Второй аргумент для if/elif в скрипте
    # command: sh -c "celery --app=app.tasks.celery_config:celery worker -l INFO"
    env_file:
      - .env-non-dev
    depends_on:
      - redis

  flower:
    image: booking_swps_flower
    build:
      context: .
    container_name: booking_swps_flower
    command: [ "/akvalenok/docker/celery.sh", "flower" ]
    # command: sh -c "celery --app=app.tasks.celery_config:celery flower"
    env_file:
      - .env-non-dev
    depends_on:
      - redis
    ports:
      - "5555:5555"

volumes:
  postgresdata:
