x-environment-defaults: &environment-defaults
  MODE: PROD
  LOG_LEVEL: INFO
  SENTRY_DSN: {{ env.SENTRY_DSN }}

  DB_NAME: akvalenok_db
  DB_USER: akvalenok_user
  DB_PASS: akvalenok_password
  DB_HOST: localhost
  DB_PORT: 5432

  TEST_DB_HOST: localhost
  TEST_DB_PORT: 5434
  TEST_DB_USER: postgres
  TEST_DB_PASS: postgres
  TEST_DB_NAME: postgres

  SECRET_KEY: {{ env.SECRET_KEY }}
  ALGORITHM: HS256
  
  REDIS_HOST: redis
  REDIS_PORT: 6379
  
  SMTP_HOST: smtp.yandex.com
  SMTP_PORT: 465
  SMTP_USER: {{ env.SMTP_USER }}
  SMTP_PASS: {{ env.SMTP_PASS }}

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: akvalenok_db
      POSTGRES_USER: akvalenok_user
      POSTGRES_PASSWORD: akvalenok_password
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: booking_swps_redis
    ports:
      - "6379:6379"
    restart: always

  akvalenok_app:
    image: {{ env.APP_IMAGE }}
    container_name: booking_swps_app
    ports:
      - "8000:8000"
    environment:
      <<: *environment-defaults
    depends_on:
      - postgres
      - redis
    command: ["/akvalenok/docker/app.sh"]
    restart: always

#  celery:
#    image: {{ env.CELERY_IMAGE }}
#    restart: always
#    container_name: booking_swps_celery
#    command: [ "/akvalenok/docker/celery.sh", "celery" ]
#    env_file:
#      - .env-non-dev
#    depends_on:
#      - redis
#
#  flower:
#    image: {{ env.FLOWER_IMAGE }}
#    restart: always
#    container_name: booking_swps_flower
#    command: [ "/akvalenok/docker/celery.sh", "flower" ]
#    env_file:
#      - .env-non-dev
#    depends_on:
#      - redis
#    ports:
#      - "5555:5555"

#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx/nginx.yc.conf:/etc/nginx/nginx.conf
#      - static_volume:/static
#    ports:
#      - "80:80"
#    depends_on:
#      - akvalenok_app
#    restart: always

volumes:
  postgresdata:
