services:
  db:
    image: postgres:16
    container_name: booking_swps_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-non-dev
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: booking_swps_redis

  akvalenok_app:
    image: {{ env.BACKEND_IMAGE }}

    container_name: booking_swps_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: ["/akvalenok/docker/app.sh"]
    ports:
      - "7777:8000"

  celery:
    image: booking_swps_celery
    build:
      context: .
    container_name: booking_swps_celery
    command: [ "/akvalenok/docker/celery.sh", "celery" ]
    env_file:
      - .env-non-dev
    depends_on:
      - redis

  flower:
    image: booking_swps_flower
    build:
      context: .
    container_name: booking_swps_flower
    command: [ "/akvalenok/docker/celery.sh", "flower" ]
    env_file:
      - .env-non-dev
    depends_on:
      - redis
    ports:
      - "5555:5555"

volumes:
  postgresdata:
